### ISSUE TITLE
Jenkins 2.89.4 - 0.6.2 plugin - WARNING: RunListener failed

### ISSUE THREAD

**Issue by bkruger99** [DataDog/jenkins-datadog-plugin#112]
I am getting runlistener failed events by the masses and I'm using spot instances.

Mar 05, 2018 5:29:41 PM hudson.model.listeners.RunListener report
WARNING: RunListener failed
java.lang.NullPointerException
        at org.datadog.jenkins.plugins.datadog.DatadogBuildListener.onStarted(DatadogBuildListener.java:113)
        at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
        at hudson.maven.MavenBuild$ProxyImpl2.start(MavenBuild.java:609)
        at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.model.Executor$2.call(Executor.java:911)
        at hudson.util.InterceptingProxy$1.invoke(InterceptingProxy.java:23)
        at com.sun.proxy.$Proxy97.start(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor161.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:922)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:896)
        at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:853)
        at hudson.remoting.UserRequest.perform(UserRequest.java:207)
        at hudson.remoting.UserRequest.perform(UserRequest.java:53)
        at hudson.remoting.Request$2.run(Request.java:358)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at org.jenkinsci.remoting.CallableDecorator.call(CallableDecorator.java:19)
        at hudson.remoting.CallableDecoratorList$1.call(CallableDecoratorList.java:21)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I'm using the latest datadog plugin and no luck.   What other information can I provide to help fix this?   This pretty much dominates my logs at this point.

thanks

**Comment by bkruger99** [comment]
Also a smaller error blob:

Mar 05, 2018 6:55:59 PM hudson.model.listeners.RunListener report
WARNING: RunListener failed
java.lang.NullPointerException
	at org.datadog.jenkins.plugins.datadog.DatadogBuildListener.onStarted(DatadogBuildListener.java:113)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.maven.MavenBuild.access$1200(MavenBuild.java:109)
	at hudson.maven.MavenBuild$ProxyImpl2.close(MavenBuild.java:693)
	at hudson.maven.AbstractMavenBuilder.end(AbstractMavenBuilder.java:107)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:885)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

**Comment by sjenriquez** [comment]
Hi @bkruger99, I've been unable to reproduce with Jenkins 2.89, if you are still having issues please reach out to support@datadoghq.com, thanks!
