### ISSUE TITLE
"DatadogBuildListener#onStarted: Unexpected exception occurred - null"

### ISSUE THREAD

**Issue by provcristianmaluenda** [DataDog/jenkins-datadog-plugin#189]
I built this plugin and I installed it in my Jenkins. We are running Jenkins in K8s using Jenkins' helm chart.
We use API configuration to send the metrics and we use multi-branch repo for our pipelines. No whitelist or blacklist is configured.
I think, because of this, we can not get all the metrics in Datadog. Some basic metrics like `jenkins.job.started` or `jenkins.job.completed` are not shown in Datadog's metrics explorer.
The same issue happens for the event `onCompleted`.

Jenkins version: `2.204.1`
Java Version: `OpenJDK 64-Bit Server VM 1.8.0_232`

Here is part of my logs:
```2019-12-30 17:02:27.615+0000 [id=544]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Datadog Counters Publisher
2019-12-30 17:02:27.615+0000 [id=544]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Datadog Counters Publisher. 0 ms
2019-12-30 17:02:37.615+0000 [id=548]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Datadog Counters Publisher
2019-12-30 17:02:37.849+0000 [id=548]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Datadog Counters Publisher. 234 ms
2019-12-30 17:02:47.615+0000 [id=559]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Datadog Counters Publisher
2019-12-30 17:02:47.843+0000 [id=562]	WARNING	o.d.j.p.d.l.DatadogBuildListener#onStarted: Unexpected exception occurred - null
2019-12-30 17:02:47.845+0000 [id=559]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Datadog Counters Publisher. 229 ms
2019-12-30 17:02:47.944+0000 [id=562]	INFO	c.s.o.i.Platform$JdkWithJettyBootPlatform#getSelectedProtocol: ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:48.040+0000 [id=564]	WARNING	o.d.j.p.d.l.DatadogBuildListener#onStarted: Unexpected exception occurred - null
2019-12-30 17:02:48.122+0000 [id=564]	INFO	c.s.o.i.Platform$JdkWithJettyBootPlatform#getSelectedProtocol: ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:53.454+0000 [id=574]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:53.755+0000 [id=577]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:54.483+0000 [id=531]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-rmhvg], container: [worker]
2019-12-30 17:02:54.781+0000 [id=546]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-3p14v], container: [worker]
2019-12-30 17:02:54.866+0000 [id=577]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:55.174+0000 [id=574]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:55.891+0000 [id=531]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-rmhvg], container: [worker]
2019-12-30 17:02:56.197+0000 [id=547]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-3p14v], container: [worker]
2019-12-30 17:02:56.262+0000 [id=577]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:56.531+0000 [id=574]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:57.299+0000 [id=525]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-rmhvg], container: [worker]
2019-12-30 17:02:57.554+0000 [id=526]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-3p14v], container: [worker]
2019-12-30 17:02:57.615+0000 [id=595]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Started Datadog Counters Publisher
2019-12-30 17:02:57.698+0000 [id=595]	INFO	hudson.model.AsyncPeriodicWork#lambda$doRun$0: Finished Datadog Counters Publisher. 82 ms
2019-12-30 17:02:58.467+0000 [id=574]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:58.574+0000 [id=577]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:02:59.494+0000 [id=524]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-rmhvg], container: [worker]
2019-12-30 17:02:59.598+0000 [id=525]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-3p14v], container: [worker]
2019-12-30 17:03:00.846+0000 [id=577]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:03:00.950+0000 [id=574]	INFO	o.internal.platform.Platform#log: ALPN callback dropped: HTTP/2 is disabled. Is alpn-boot on the boot class path?
2019-12-30 17:03:01.870+0000 [id=525]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-rmhvg], container: [worker]
2019-12-30 17:03:01.976+0000 [id=524]	INFO	o.c.j.p.k.p.ContainerExecDecorator$1#doLaunch: Created process inside pod: [debian-10-3p14v], container: [worker]
2019-12-30 17:03:03.418+0000 [id=524]	INFO	o.j.p.workflow.job.WorkflowRun#finish: devex/jenkins-test/master #218 completed: SUCCESS
2019-12-30 17:03:03.470+0000 [id=80]	SEVERE	c.s.s.utils.LogConsumer#run: message not delivered:{raw data{event_tag=build_report, metadata={scm_url=null, scm=git, branch=null, revision=null}, job_name=devex/jenkins-test/master, testsuite=failures: 0, passes: 0, ...}
com.splunk.splunkjenkins.utils.LogConsumer$SplunkClientError: Bad Request, incorrect index or invalid data format, status code:400
	at com.splunk.splunkjenkins.utils.LogConsumer$1.handleResponse(LogConsumer.java:68)
	at com.splunk.splunkjenkins.utils.LogConsumer$1.handleResponse(LogConsumer.java:40)
	at shaded.splk.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at shaded.splk.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at shaded.splk.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at com.splunk.splunkjenkins.utils.LogConsumer.run(LogConsumer.java:89)
2019-12-30 17:03:03.474+0000 [id=524]	WARNING	o.d.j.p.d.l.DatadogBuildListener#onCompleted: Unexpected exception occurred - null
2019-12-30 17:03:03.569+0000 [id=529]	INFO	o.j.p.workflow.job.WorkflowRun#finish: devex/jenkins-test/master #219 completed: SUCCESS
2019-12-30 17:03:03.592+0000 [id=80]	SEVERE	c.s.s.utils.LogConsumer#run: message not delivered:{raw data{event_tag=build_report, metadata={scm_url=null, scm=git, branch=null, revision=null}, job_name=devex/jenkins-test/master, testsuite=failures: 0, passes: 0, ...}
com.splunk.splunkjenkins.utils.LogConsumer$SplunkClientError: Bad Request, incorrect index or invalid data format, status code:400
	at com.splunk.splunkjenkins.utils.LogConsumer$1.handleResponse(LogConsumer.java:68)
	at com.splunk.splunkjenkins.utils.LogConsumer$1.handleResponse(LogConsumer.java:40)
	at shaded.splk.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at shaded.splk.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at shaded.splk.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at com.splunk.splunkjenkins.utils.LogConsumer.run(LogConsumer.java:89)
2019-12-30 17:03:03.596+0000 [id=529]	WARNING	o.d.j.p.d.l.DatadogBuildListener#onCompleted: Unexpected exception occurred - null
```

Regards,
Cristian.

**Comment by jeremy-lq** [comment]
Closing this issue as we've moved to a support ticket based on: https://github.com/DataDog/jenkins-datadog-plugin/issues/188
