### ISSUE TITLE
java.lang.NullPointerException with DD 0.5.1 on Jenkins 2.9

### ISSUE THREAD

**Issue by aaronkvanmeerten** [DataDog/jenkins-datadog-plugin#46]
I am using the datadog plugin version 0.5.1 with jenkins version 2.9, and in the jenkins log I see the following.  Although my API key seems to check out fine using the system control panel, no events make it to DataDog.  Any suggestions?

`WARNING: RunListener failed
java.lang.NullPointerException
	at org.datadog.jenkins.plugins.datadog.DatadogUtilities.parseTagList(DatadogUtilities.java:105)
	at org.datadog.jenkins.plugins.datadog.DatadogBuildListener.onStarted(DatadogBuildListener.java:103)
	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
	at hudson.model.Run.execute(Run.java:1716)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)`

**Comment by JohnLZeller** [comment]
Hey @aaronkvanmeerten! Thank you for bringing this to our attention. We will take a look at this, and a bugfix release might be in order. I'll let you know if I have any more questions.

**Comment by lesaux** [comment]
I am seeing this as well.

**Comment by rgulewich** [comment]
Seeing this too - Jenkins version 1.642.2, plugin version 0.5.1

**Comment by bcarl** [comment]
Seeing this as well, Jenkins 2.0, plugin version 0.5.1

**Comment by JohnLZeller** [comment]
[0.5.2](https://github.com/jenkinsci/datadog-plugin/releases/tag/datadog-0.5.2) fixes this. It should be available through the Update Center within ~4 hours.

[Release is here](https://github.com/jenkinsci/datadog-plugin/releases/tag/datadog-0.5.2)
